import { useState } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { Search, TrendingUp, Database, Bot, ArrowRight } from "lucide-react";
import Hero3D from "../components/Hero3D";

const stats = [
  { icon: Database, label: "Companies Indexed", value: "5,000+" },
  { icon: TrendingUp, label: "Reports Generated", value: "12,400+" },
  { icon: Bot, label: "AI Queries Answered", value: "38,900+" },
];

const quickTickers = ["NVDA", "AAPL", "TSLA", "AMD"];

export default function HomePage() {
  const [ticker, setTicker] = useState("");
  const navigate = useNavigate();

  const handleSearch = (t?: string) => {
    const val = (t ?? ticker).trim();
    if (!val) return;
    navigate(`/dashboard/${val.toUpperCase()}`);
  };

  return (
    <div className="relative min-h-[90vh] flex flex-col items-center justify-center px-6 overflow-hidden">
      <Hero3D />

      <motion.div
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center gap-2 mb-6 glass px-3 py-1.5 rounded-full"
      >
        <span className="live-dot" />
        <span className="font-mono text-[11px] text-terminal-muted tracking-widest uppercase">
          Markets Live · AI Engine Online
        </span>
      </motion.div>

      <motion.h1
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="font-display text-5xl md:text-7xl font-bold text-center tracking-tight"
      >
        ALPHA
        <span className="bg-gradient-to-r from-terminal-cyan to-terminal-blue bg-clip-text text-transparent">
          FORGE
        </span>
      </motion.h1>

      <motion.p
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.15 }}
        className="text-terminal-muted mt-4 text-center max-w-xl text-sm md:text-base"
      >
        Equity research, financials, and conversational analysis —
        <span className="text-terminal-text"> generated by AI, terminal-grade.</span>
      </motion.p>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.3 }}
        className="glass glow-cyan mt-10 w-full max-w-xl rounded-xl p-2 flex items-center gap-2"
      >
        <Search className="text-terminal-cyan ml-3" size={20} />
        <input
          value={ticker}
          onChange={(e) => setTicker(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && handleSearch()}
          placeholder="Enter ticker symbol (e.g. AAPL, TSLA, RELIANCE)"
          className="bg-transparent flex-1 outline-none font-mono text-sm py-3 placeholder:text-terminal-muted"
        />
        <button
          onClick={() => handleSearch()}
          className="group bg-terminal-cyan text-terminal-bg font-mono text-sm font-semibold px-5 py-3 rounded-lg hover:bg-cyan-400 transition-all flex items-center gap-1.5"
        >
          Analyze
          <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
        </button>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="flex gap-2 mt-4"
      >
        {quickTickers.map((t) => (
          <button
            key={t}
            onClick={() => handleSearch(t)}
            className="font-mono text-xs text-terminal-muted hover:text-terminal-cyan border border-terminal-border hover:border-terminal-cyan/40 rounded-full px-3 py-1 transition-colors"
          >
            {t}
          </button>
        ))}
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6, delay: 0.55 }}
        className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-16 w-full max-w-3xl"
      >
        {stats.map(({ icon: Icon, label, value }, i) => (
          <motion.div
            key={label}
            whileHover={{ scale: 1.02 }}
            className="glass card-hover rounded-xl p-5 flex flex-col items-center gap-2 relative overflow-hidden"
          >
            <div className="absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-terminal-cyan/0 via-terminal-cyan/60 to-terminal-cyan/0" />
            <Icon className="text-terminal-cyan" size={22} />
            <div className="font-display text-2xl font-bold">{value}</div>
            <div className="text-terminal-muted text-xs font-mono text-center uppercase tracking-wide">
              {label}
            </div>
          </motion.div>
        ))}
      </motion.div>
    </div>
  );
}
